### PR TITLE
ARUHA-1275 upgrade json-schema version

### PR DESCRIPTION
**Pull request by lmontrieux**
Also upgrade org.json version

ARUHA-1275: Get json-schema optimisation merged and released

## Description
Upgrade version of json-schema library, with performance improvements

## Review
- [ ] Tests
- [ ] Documentation
- [x] CHANGELOG

## Deployment Notes
These should highlight any db migrations, feature toggles, etc.

### CODE REVIEW

**Comment by lmontrieux** [comment]
👎

**Comment by lmontrieux** [comment]
This is WIP

**Comment by lmontrieux** [comment]
👍

**Comment by adyach** [comment]
👍

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
👎  found an issue with schemas containing references

**Comment by lmontrieux** [comment]
👎

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
deploy validation please

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
Deploy validation please

**Pull request merged**
