### PR TITLE
Upgrade spring version

### PR DESCRIPTION
**Pull request by tor-vs-floki**
Bump spring version to the newsest one

### CODE REVIEW

**Comment by a1exsh** [comment]
So we don't need to change [`application.yml`](https://github.com/zalando/nakadi/pull/1384/commits/da0b9f30dfd91a797c062e4cbb84fc355a93246e#diff-cfaac170cb673164b4d30a6ae0f20631762be4126821b99e86a4421f09bf4fda) for this to work?  Does Spring automatically convert the config value to `String[]` properly?

**Comment by tor-vs-floki** [comment]
> So we don't need to change [`application.yml`](https://github.com/zalando/nakadi/pull/1384/commits/da0b9f30dfd91a797c062e4cbb84fc355a93246e#diff-cfaac170cb673164b4d30a6ae0f20631762be4126821b99e86a4421f09bf4fda) for this to work? Does Spring automatically convert the config value to `String[]` properly?

Yes, exactly. Spring will convert comma-separated strings into String[].

**Comment by a1exsh** [comment]
:+1:

**Comment by tor-vs-floki** [comment]
👍

**Pull request merged**
