### PR TITLE
aruha-114 refactoring event type validation

### PR DESCRIPTION
**Pull request by rcillo**
Event type validation is a source of confusion and possibly bugs. In
order to make it clearer and easier to understand, I'm reducing the
amount of branches and logic, using exceptions in a smarter and more
homogeneous way.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/171" target="_blank">ReviewNinja

**Comment by v-stepanov** [comment]
:shipit:

**Comment by rcillo** [comment]
@v-stepanov I added one more commit https://github.com/zalando/nakadi/commit/1654663bb75ee76bfc0efc90f15ceb63738daa96

**Comment by v-stepanov** [comment]
:shipit:

**Comment by rcillo** [comment]
Solved a conflict merge and lost my :star:

**Comment by v-stepanov** [comment]
:shipit:

**Pull request merged**
