### PR TITLE
ARUHA-192: enabled auth logging; enabled nakadi debug logging;

### PR DESCRIPTION
**Pull request by v-stepanov**
@rcillo @antban @jkliff please review

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/244" target="_blank">ReviewNinja

**Comment by rcillo** [comment]
Is Nakadi DEBUG overwritten in production? That would generate a lot of logging.

**Comment by v-stepanov** [comment]
@rcillo 
I don't think that it will be too much. Nakadi logs to debug only if some problem happens. In successful case it doesn't log anything. 

Also, oauth logging will generate much more logging - for each request it will generate 4 lines of log. 

I think that for current stage this is ok, as we don't have any high traffic yet.
What do you think?

**Comment by rcillo** [comment]
Maybe you have a point. It could help debug issues in the early stages. I'm just skeptical about keeping it in the long run. And this arrises the question: when should we turn it off?

**Comment by v-stepanov** [comment]
@rcillo  we will switch it off when we have a fuckup because we run out of disk space because of too much logs :-D

If to be serious:
1) I think we can switch off nakadi debug logs as soon as few teams use nakadi and everything is ok for them.
2) And we can switch off oauth logs when we have that basic security improvement (for now we need at least to know who modifies what)

**Comment by rcillo** [comment]
👍 looks good.

🚢 🇮🇹

**Comment by rcillo** [comment]
Could you please post an example of how it looks like (auth in the logs)?

**Comment by v-stepanov** [comment]
@rcillo 
```
[2016-05-17 07:41:30.820] AW0d322YLgziOk7YXNw6S1MD boot - 5 DEBUG [http-nio-8080-exec-6] --- FilterSecurityInterceptor: Secure object: FilterInvocation: URL: /event-types/fdsfds; Attributes: [#oauth2.throwOnError(#oauth2.hasScope('uid'))]
[2016-05-17 07:41:30.820] AW0d322YLgziOk7YXNw6S1MD boot - 5 DEBUG [http-nio-8080-exec-6] --- FilterSecurityInterceptor: Previously Authenticated: org.springframework.security.oauth2.provider.OAuth2Authentication@4fc17666: Principal: stups_aruha-access-checker; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=10.0.2.2, tokenType=BearertokenValue=<TOKEN>; Granted Authorities: ROLE_USER
[2016-05-17 07:41:30.822] AW0d322YLgziOk7YXNw6S1MD boot - 5 DEBUG [http-nio-8080-exec-6] --- FilterSecurityInterceptor: Authorization successful
[2016-05-17 07:41:30.822] AW0d322YLgziOk7YXNw6S1MD boot - 5 DEBUG [http-nio-8080-exec-6] --- FilterSecurityInterceptor: RunAsManager did not change Authentication object`
```

**Pull request merged**
