### PR TITLE
ARUHA-1520: added possibility to read both versions of Session from ZK;

### PR DESCRIPTION
**Pull request by v-stepanov**
# Added possibility to read both versions of subscriptions.

> Zalando ticket : ARUHA-1520 (only if appropriate)

## Description
This is just a fix to be able to release https://github.com/zalando/nakadi/pull/848

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
-

### CODE REVIEW

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
