### PR TITLE
ARUHA-280 Remove network_mode:host + no links

### LINKED ISSUE #413: Problems with Network Mode: Host
In the current local Nakadi appliance, I experience problems with the network_mode _host_ (I would need to set up my iptables etc to get it work (see also http://www.dasblinkenlichten.com/docker-networking-101-host-mode/)). Actually, you could also design the docker-compose file with _links_:

``` yml
version: '2'
services:

  nakadi:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - postgres
     - zookeeper
     - kafka
    environment:
      - SPRING_PROFILES_ACTIVE
      - NAKADI_OAUTH2_MODE=OFF
      - NAKADI_FEATURETOGGLE_DEFAULT=true
      - NAKADI_ZOOKEEPER_BROKERS=zookeeper:2181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/local_nakadi_db
      - SPRING_DATASOURCE_USERNAME=nakadi
      - SPRING_DATASOURCE_PASSWORD=nakadi
    links:
      - zookeeper:zookeeper
      - postgres:postgres

  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - "./database/nakadi:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: nakadi
      POSTGRES_PASSWORD: nakadi
      POSTGRES_DB: local_nakadi_db

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.9.0.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "test-topic:8:1"
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

I will prepare a corresponding Pull Request.

### PR DESCRIPTION
**Pull request by elgalu**
Closes #413 #414

### CODE REVIEW

**Comment by adyach** [comment]
@elgalu could you please update docker-compose version in travis.yml?

**Comment by adyach** [comment]
@elgalu a lot of tests failed, looks like some general problem(at a glance kafka connection issue). If you have time, please, take a look. it is also possible to run tests locally with the command: `./gradlew fullAcceptanceTest`

**Comment by elgalu** [comment]
Hi @adyach , I was unable to run the tests as they already fail for me in the master branch, e.g.
https://gist.github.com/elgalu/cb697c081e1659229b1e244cb8917e93

Perhaps some misconfiguration? Travis is also failing in the master branch.

**Comment by adyach** [comment]
@elgalu either your Kafka container is not running or not accessible:
`kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0`

About master branch: if you talk about the label on the github It actually shows the latest build from the latest committed branch (should be fixed imho).

**Comment by elgalu** [comment]
About the master branch, I think the last builds failed there, see:

image

**Comment by lmontrieux** [comment]
@elgalu thank you very much for your contribution. I think fixing local deployments is very important, but sadly we haven't had much time to get to it ourselves.

The last 3 builds of master are passing, as I write these lines. we are aware of a few tests that routinely hit their timeouts, and we have plans to address this.

Did you get a chance to make progress on this?

**Comment by elgalu** [comment]
Hi @lmontrieux, glad to hear is passing in the master branch!

I won't be working on this for the time being, feel free to close this PR, it may still be used as a reference in the future anyways;)

**Comment by lmontrieux** [comment]
Thanks for your reply, @elgalu . I'll keep the PR open for a bit, hoping to find some time to look into it. I'm tagging this PR with 'help wanted', in case someone else wants to contribute.

**Comment by mqzry** [comment]
I wasted some time creating my own exact copy of this pull request in my own branch because it is kinda hidden.  This makes my startNakadi task work completely on my mac. I would recommend to communicate this fix in the 'Getting started' section.

Not everybody uses linux.

**Comment by lmontrieux** [comment]
@mqzry Thank you for your comment, and for using Nakadi. Unfortunately, the tests still seem to fail for this. Could you try to run them locally (`./gradlew fullTest`) and report the results?

By the way, Nakadi does work fine on mac os, but only with docker toolbox (not docker for mac). I'd be more than happy to merge a PR that puts this issue to rest, without causing issues with docker toolbox on mac os or docker on Linux.

**Comment by mqzry** [comment]
Results: 1 failed test. Namely 'KafkaTopicRepositoryTest.whenKafkaPublishTimeoutThenCircuitIsOpened'

**Comment by adyach** [comment]
I believe it was fixed in #980

**Pull request closed without merging**
