### PR TITLE
Fix typo: getLocalTokenInfoUrl()

### PR DESCRIPTION
**Pull request by a1exsh**
Fix copy/paste problem in `AuthenticationConfig` class.

### CODE REVIEW

**Comment by adyach** [comment]
👍

**Comment by antban** [comment]
@a1exsh does it mean that we never used local token info?

**Comment by a1exsh** [comment]
> @a1exsh does it mean that we never used local token info?

Probably we did before that refactoring 18 months ago. ;)

**Comment by antban** [comment]
:+1:

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
