### PR TITLE
ARUHA-1181 Use RackAwareMode.Safe while creating topics

### PR DESCRIPTION
**Pull request by antban**
[ARUHA-1181: Use rack awareness kafka feature in a safe way]

## Description
Use rack awareness kafka feature in a safe way

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
Nakadi change should be deployed before adding rack_id on kafka side.

### CODE REVIEW

**Comment by adyach** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Comment by antban** [comment]
deploy validation please

**Comment by antban** [comment]
deploy validation please

**Pull request merged**
