### PR TITLE
issue-596 fix pattern comparison

### LINKED ISSUE #596: Unable to update an EventType if one of the fields has a pattern
When I try to update an EventType containing a field with a pattern definition I always get a HTTP Status Code 422 Unprocessable Entity (note that the pattern isn't changing).

How to reproduce:

1. Create an Event Type containing a field with a pattern:

`curl -v -XPOST -H "Content-Type: application/json" -H "Authorization: Bearer $(ztoken token)" https://nakadi-staging.aruha-test.zalan.do/event-types -d '{
  "name": "update-test",
  "owning_application": "purchase-orders-management",
  "category": "data",
  "enrichment_strategies": [
    "metadata_enrichment"
  ],
  "partition_strategy": "hash",
  "compatibility_mode": "forward",
  "partition_key_fields": [
    "code"
  ],
  "schema": {
    "type": "json_schema",
    "schema": "{\"title\":\"Test\",\"type\":\"object\",\"description\":\"Test\",\"properties\":{\"first\":{\"type\":\"string\",\"description\":\"A string with a pattern\",\"pattern\":\"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"}}}"
  },
  "default_statistic": {
    "messages_per_minute": 100,
    "message_size": 5000,
    "read_parallelism": 4,
    "write_parallelism": 4
  }
}'`

2. Update the event adding a second field:

`curl -v -XPUT -H "Content-Type: application/json" -H "Authorization: Bearer $(ztoken token)" https://nakadi-staging.aruha-test.zalan.do/event-types/update-test -d '{
  "name": "update-test",
  "owning_application": "purchase-orders-management",
  "category": "data",
  "enrichment_strategies": [
    "metadata_enrichment"
  ],
  "partition_strategy": "hash",
  "compatibility_mode": "forward",
  "partition_key_fields": [
    "code"
  ],
  "schema": {
    "type": "json_schema",
    "schema": "{\"title\":\"Test\",\"type\":\"object\",\"description\":\"Test\",\"properties\":{\"first\":{\"type\":\"string\",\"description\":\"A string with a pattern\",\"pattern\":\"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"},\"second\":{\"type\":\"string\",\"description\":\"A new field\"}}}"
  },
  "default_statistic": {
    "messages_per_minute": 100,
    "message_size": 5000,
    "read_parallelism": 4,
    "write_parallelism": 4
  }
}'`

Nakadi responds with following error:

`{"type":"http://httpstatus.es/422","title":"Unprocessable Entity","status":422,"detail":"Invalid schema: #/properties/first/pattern: change to attribute value not allowed"}`

Same scenario without pattern definition works ok:
`curl -v -XDELETE -H "Authorization: Bearer $(ztoken token)" https://nakadi-staging.aruha-test.zalan.do/event-types/update-test`

`curl -v -XPOST -H "Content-Type: application/json" -H "Authorization: Bearer $(ztoken token)" https://nakadi-staging.aruha-test.zalan.do/event-types -d '{
  "name": "update-test",
  "owning_application": "purchase-orders-management",
  "category": "data",
  "enrichment_strategies": [
    "metadata_enrichment"
  ],
  "partition_strategy": "hash",
  "compatibility_mode": "forward",
  "partition_key_fields": [
    "code"
  ],
  "schema": {
    "type": "json_schema",
    "schema": "{\"title\":\"Test\",\"type\":\"object\",\"description\":\"Test\",\"properties\":{\"first\":{\"type\":\"string\",\"description\":\"A string without a pattern\"}}}"
  },
  "default_statistic": {
    "messages_per_minute": 100,
    "message_size": 5000,
    "read_parallelism": 4,
    "write_parallelism": 4
  }
}'`

`curl -v -XPUT -H "Content-Type: application/json" -H "Authorization: Bearer $(ztoken token)" https://nakadi-staging.aruha-test.zalan.do/event-types/update-test -d '{
  "name": "update-test",
  "owning_application": "purchase-orders-management",
  "category": "data",
  "enrichment_strategies": [
    "metadata_enrichment"
  ],
  "partition_strategy": "hash",
  "compatibility_mode": "forward",
  "partition_key_fields": [
    "code"
  ],
  "schema": {
    "type": "json_schema",
    "schema": "{\"title\":\"Test\",\"type\":\"object\",\"description\":\"Test\",\"properties\":{\"first\":{\"type\":\"string\",\"description\":\"A string without a pattern\"},\"second\":{\"type\":\"string\",\"description\":\"A new field\"}}}"
  },
  "default_statistic": {
    "messages_per_minute": 100,
    "message_size": 5000,
    "read_parallelism": 4,
    "write_parallelism": 4
  }
}'`

### PR DESCRIPTION
**Pull request by rcillo**
Fix #596

### CODE REVIEW

**Comment by adyach** [comment]
:shipit:

**Comment by adyach** [comment]
:shipit:

**Comment by rcillo** [comment]
@adyach added one more test case and fixed a possible null pointer https://github.com/zalando/nakadi/pull/597/commits/8932f0d9ef4d6247005877e360a0eca2e2b74839

**Comment by adyach** [comment]
:shipit:

**Comment by rcillo** [comment]
@adyach zappr is messed up. Could you try to approve again, please?

**Comment by adyach** [comment]
:shipit:

**Comment by adyach** [comment]
👍

**Comment by rcillo** [comment]
@adyach let's try once more? I don't know what is going on with zappr =/

**Comment by adyach** [comment]
:shipit:

**Comment by rcillo** [comment]
👍

**Comment by adyach** [comment]
👍

**Pull request merged**
