### PR TITLE
ARUHA-240: Edits to API definition

### PR DESCRIPTION
**Pull request by dehora**
A collection of tweaks and edits to the API definition mostly to optimise for reading in the documentation or via the Swagger UI.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/282" target="_blank">ReviewNinja

**Comment by rcillo** [comment]
@dehora unfortunately, after merging some previous PRs, it seems that this one requires merge fix.

**Comment by dehora** [comment]
thanks for the ping @rcillo; I'll rebase this soon.

**Comment by dehora** [comment]
rebased

**Comment by dehora** [comment]
rebased / @rcillo

**Pull request merged**
