### PR TITLE
updated token info URL

### PR DESCRIPTION
**Pull request by v-stepanov**
@tmuehl @jkliff @CyberDem0n @rcillo please review

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/130" target="_blank">ReviewNinja

**Comment by drummerwolli** [comment]
shouldn't something like this be configured at runtime for an opensource project? this is basically a zalando internal endpoint ...

**Comment by tmuehl** [comment]
@drummerwolli +1

**Comment by tmuehl** [comment]
@drummerwolli agree

**Comment by v-stepanov** [comment]
@drummerwolli @tmuehl 
Agree. We were too lazy to do that from the beginning :)
I will close this PR and will open another one

**Pull request closed without merging**
