### PR TITLE
Add go-nakadi library to the list of Nakadi clients

### PR DESCRIPTION
**Pull request by stoewer**
## Description

The [`go-nakadi`](https://github.com/stoewer/go-nakadi) package provides a Nakadi client library for the Go programming language. Although the project is rather new, the client still provides a feature rich and well tested API. It would be great if the Nakadi maintainers could have a look at the `go-nakadi` package and add it to the list of available clients in Nakadi's documentation. Every feedback on `go-nakadi` is very welcome.

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
Just an amendment for the documentation, nothing special here.

### CODE REVIEW

**Comment by stoewer** [comment]
:+1:

**Comment by lmontrieux** [comment]
Thank you for your contribution. I see more and more clients in various languages, this is great!

**Comment by lmontrieux** [comment]
👍

**Comment by SergKam** [comment]
:+1:

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
