### PR TITLE
INC-13145 Do not log stack trace when users provide a non-existing subscription ID

### PR DESCRIPTION
**Pull request by lmontrieux**
# Do not log stack trace when users provide a non-existing subscription ID

> Zalando ticket : INC-13145

## Description
This PR stops logging a full stack trace when a users makes a GET request to `/subscriptions/{id}` or `/subscriptions/{id}/events` with a subscription ID that does not exist

### CODE REVIEW

**Comment by adyach** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by rcillo** [comment]
👍

**Pull request merged**
