### PR TITLE
ARUHA-964: reformated imports;

### PR DESCRIPTION
**Pull request by v-stepanov**
[ARUHA-964: Reformat Imports](https://techjira.zalando.net/browse/ARUHA-964)

## Description
Some old PRs brought wrong import format for some files. This is second iteration of formatting imports.

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
nothing to deploy

### CODE REVIEW

**Comment by rcillo** [comment]
👍

**Comment by rcillo** [comment]
@v-stepanov please add a changelog entry.

**Comment by v-stepanov** [comment]
👍

**Comment by v-stepanov** [comment]
@rcillo tada https://github.com/zalando/nakadi/pull/726/commits/2f795a6288aa4b99efdd1a135e5a68aa1a22577b

**Comment by v-stepanov** [comment]
👍

**Comment by rcillo** [comment]
👍

**Pull request merged**
