### PR TITLE
(fixed #14) added logging of request and response for some cases; ext…

### LINKED ISSUE #14: Improve logging of errors of push-endpoint
We need to improve the logging of push-endpoint. Currently if error-response is created on connexion-level we don't have too much log data about that. We just have simple access log from gunicorn:

> [02/Nov/2015:13:03:10 +0000] "POST /topics/eventstore.article.16/events HTTP/1.1" 400 152 "-" "Java/1.8.0_05"

But in this case we need at least to see the request body.
First we need to check if it is possible to configure connexion to log request body in a case of creation of error-response.

### PR DESCRIPTION
**Pull request by v-stepanov**
@valgog @jkliff @tmuehl feedback welcomed

### CODE REVIEW

**Comment by v-stepanov** [comment]
Of course the best way would be to dump request body only in a case of error status_code, but due to implementation of gunicorn, the request body is not available at the post_request hook.

**Comment by tmuehl** [comment]
I like having the gunicorn config in a separate file.

**Comment by v-stepanov** [comment]
@tmuehl yeah, mee too. But this branch never went to master as it doesn't actually work on AWS. So the separation of gunicorn didn't go to master as well :)

**Comment by tmuehl** [comment]
Why does it now work on AWS?

**Comment by v-stepanov** [comment]
I don't know. The logging of response body just didn't work there :( However it worked pretty fine locally.

**Comment by valgog** [comment]
I will close the PR because we will not investigate on that further.

**Pull request closed without merging**
