### PR TITLE
ARUHA-1168: added logging of POST requests with compressed body;

### PR DESCRIPTION
**Pull request by v-stepanov**
[ARUHA-1168: Log usage of request body compression](https://techjira.zalando.net/browse/ARUHA-1168)

## Description
Added logging of POST requests with compressed body.

## Review
- [ ] Tests
- [ ] Documentation
- [x] CHANGELOG

## Deployment Notes
<none>

### CODE REVIEW

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
build validation please

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
