### PR TITLE
ARUHA-960: reverted feature toggle CHECK_APPLICATION_LEVEL_PERMISSION…

### PR DESCRIPTION
**Pull request by v-stepanov**
…S deletion;

[ARUHA-960](https://techjira.zalando.net/browse/ARUHA-960)

## Description
Reverted the deletion of Feature Toggle for checking ET read/write scopes

## Review
- [ ] Tests
- [ ] Documentation
- [x] CHANGELOG

## Deployment Notes
-

### CODE REVIEW

**Comment by lmontrieux** [comment]
Can you update the changelog, for a new version (1.1.1)?

**Comment by v-stepanov** [comment]
@lmontrieux done

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
