### PR TITLE
super small typo

### PR DESCRIPTION
**Pull request by drummerwolli**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/105" target="_blank">ReviewNinja

**Comment by v-stepanov** [comment]
@drummerwolli I believe it should be actually even `standardized`

**Comment by drummerwolli** [comment]
hahaha, omg ... fixed ...

**Comment by v-stepanov** [comment]
cool, thanks

**Pull request merged**
