### PR TITLE
Aruha 238 fix short circuit bug

### PR DESCRIPTION
**Pull request by v-stepanov**
@antban @rcillo @jkliff please review.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/300" target="_blank">ReviewNinja

**Comment by v-stepanov** [comment]
doublefacepalm

**Comment by rcillo** [comment]
When reviewing this I actually thought that we wanted to abort commits if there's an error in one of then.

**Comment by antban** [comment]
I'm fine with it
:shipit:

**Comment by v-stepanov** [comment]
@rcillo 
No, I actually don't see a good reason to skip the rest. What if all other cursors are valid to commit.

**Comment by rcillo** [comment]
:shipit:

**Pull request merged**
