### PR TITLE
Fix kafka circuit breaker to switch to open state multiple times

### PR DESCRIPTION
**Pull request by max-neverov**
# One-line summary
Fix kafka circuit breaker to switch to open state multiple times.

## Description
Once transit to `Open` state KafkaCircuitBreaker will preserve this state forever.  

There are two problems:
- `HystrixKafkaCircuitBreaker` doesn't update `circuitOpened` on fail. This causes `com.netflix.hystrix.HystrixCircuitBreaker.HystrixCircuitBreakerImpl#isAfterSleepWindow` always passes and `allowRequest` will always return true after the window.
Fixed by adding `circuitBreaker.markNonSuccess();`
- `KafkaTopicRepository` uses `allowRequest`. This is the reason why the circuit breaker will never transit from `Open` to `HalfOpen` state and from `HalfOpen` to `Close`. Fixed by using `attemptExecution` instead.

To reproduce the issue checkout the branch, revert changes in `HystrixKafkaCircuitBreaker` and `KafkaTopicRepository` and run `KafkaTopicRepositoryTest#whenKafkaPublishTimeoutThenCircuitIsOpened`. 

Relates to https://github.com/zalando/nakadi/issues/741:
It is better to use shrinked health check interval instead of thread sleep because current implementation takes 15 seconds to run tests. It can be fixed after merge of #741 to master.

Relates to #1037:
 I would prefer to write a separate test on this issue, but it is a lot of redundant and misleading code since `KafkaTopicRepositoryTest` uses a shared circuit. So I crammed the circuit breaker's state test to the existing test.

## Review
- [ ] Tests
- [ ] Documentation

## Deployment Notes
These should highlight any db migrations, feature toggles, etc.

### CODE REVIEW

**Comment by adyach** [comment]
@max-neverov thank you for contribution! 
I am not sure why I have implemented it this way back then, it looks like a bug at the moment.
Please, fix checkstyle issue which travis reports.

**Comment by max-neverov** [comment]
@adyach done.
The `attemptExecution` method was added to Hystrix in 2017, so at the time `HystrixKafkaCircuitBreaker` was implemented there was no such method.

**Comment by adyach** [comment]
👍

**Comment by max-neverov** [comment]
@adyach 
I merged master and added some more circuit breaker params to reduce the test run time (before ~15sec for the whole class, now ~3sec), ptal

**Comment by adyach** [comment]
👍

**Comment by lmontrieux** [comment]
@max-neverov I'm doing a bit of cleanup, and it looks like we failed to follow up on your PR. Really sorry about that :(.

Would you mind fixing the conflict, so we can merge this asap? Thanks a lot!

**Comment by max-neverov** [comment]
Hi @lmontrieux, 

please check the attached patch for the test
[Merge_with_master.patch.txt](https://github.com/zalando/nakadi/files/3597440/Merge_with_master.patch.txt)

**Comment by adyach** [comment]
closed in  #1112

**Pull request closed without merging**
