### PR TITLE
ARUHA-1075 Add authorization table to DB

### PR DESCRIPTION
**Pull request by lmontrieux**
[ARUHA-1075: Add authorization table to DB](https://techjira.zalando.net/browse/ARUHA-1075)

## Description
A new table for authorization

## Review
- [ ] Tests
- [ ] Documentation
- [x] CHANGELOG

## Deployment Notes
This PR only contains a new table for authorization. Deployment of this PR to an existing version of Nakadi is limited to running the migration script `database/migration/aruha-1075-authorization.sql` on the database. It is possible to use older versions of Nakadi with this additional table.

### CODE REVIEW

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
@lmontrieux please also create sql migration file in `database/migration`

**Comment by lmontrieux** [comment]
@v-stepanov dd526ad

**Comment by v-stepanov** [comment]
👍

**Comment by rcillo** [comment]
@lmontrieux this PR lacks description on "Deployment notes".

**Comment by lmontrieux** [comment]
@rcillo updated the PR description and fixed merge conflict

**Comment by rcillo** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
