### PR TITLE
More specific `date-time` format in the API docs

### LINKED ISSUE #814: Unspecific date-time format in docs
The timestamps in the API docs could be more specific than `date-time` for easier client integration.

### PR DESCRIPTION
**Pull request by amrhassan**
[ARUHA-814: Unspecific date-time format in docs](https://github.com/zalando/nakadi/issues/814)

## Description
Added date-time format standard name to the API docs. (Closes #814)

## Review
- [ ] ~Tests~
- [x] Documentation
- [ ] ~CHANGELOG~

## Deployment Notes
None.

### CODE REVIEW

**Comment by lmontrieux** [comment]
Thank you for your contribution, @amrhassan

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by v-stepanov** [comment]
@amrhassan thanks for your contribution. I merged the PR.

**Pull request merged**
