### PR TITLE
aruha-507 remove support for allOf

### PR DESCRIPTION
**Pull request by rcillo**
Description of the problem https://techjira.zalando.net/browse/ARUHA-507

### CODE REVIEW

**Comment by lmontrieux** [comment]
:shipit:

**Comment by lmontrieux** [comment]
There are style issues, which apparently stem from the new rule that `if` must always use curly brackets. Other than that, it look good :)

**Comment by rcillo** [comment]
@lmontrieux @v-stepanov @antban I thought more about this problem and I have another proposal, instead of deprecating support for it.

Ideally, we should validate `allOf` as usual, without strict validation. But after it passes, we should be sure that no properties were left outside during validation. What I mean is that we should have 100% coverage of the event during validation, which is different from being strict.

Imagine that every time an event property is validated against a sub-schema we "mark" it as covered. Then, the problem is to check if the entire event was covered.

So, we could merge this and reintroduce support in the future once this has been implemented.

Since we have a new compatibility mode `forward` this `allOf` restriction won't affect our users.

**Comment by rcillo** [comment]
There is also another possibility under discussion, which would involve the data-lake dropping properties that were not covered. So we would accept events without strict mode and it would be handled afterwards by the data-lake.

**Comment by v-stepanov** [comment]
@rcillo 
> Ideally, we should validate allOf as usual, without strict validation. But after it passes, we should be sure that no properties were left outside during validation.
I don't really know. Does it change the default behavior of JSON-schema?

**Comment by rcillo** [comment]
@v-stepanov I describe [here](https://docs.google.com/document/d/1FmGHxI9oklxN16LKZe1UG_U21jtQFVCtLtRiC2W1pAk/edit#heading=h.7hwuy21sl20) what I tried to achieve with strict validation.

The problem is that it's not trivial to implement and it's very specific to the problem we have in hands - supporting data-lake requirements for backward compatibility.

The way I chose to implement it, by forcing additionalProperties to false, had the side-effect of breaking `allOf`. We should either choose to implement another approach, or deprecate the support for `allOf`.

**Comment by lmontrieux** [comment]
@rcillo @v-stepanov are we going ahead with this solution, or are we still discussing alternatives?

**Comment by rcillo** [comment]
@lmontrieux let's discuss it on our weekly tech alignment. I'll further explain the problem, the options and we can decide what to do.

**Comment by rcillo** [comment]
As discussed in our alignment meeting. https://techjira.zalando.net/browse/ARUHA-507?focusedCommentId=1685455&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1685455

**Pull request closed without merging**
