### PR TITLE
This unchecked cast causes a warning

### PR DESCRIPTION
**Pull request by tmuehl**
...that breaks the build if the compiler is configured to be restrictive.

@v-stepanov @CyberDem0n @rcillo @jkliff Please review

Any better suggestion to get rid of that warning?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/147" target="_blank">ReviewNinja

**Comment by rcillo** [comment]
Do you think it would be a good idea to make our build more restrictive, so we would have feedback from travis on our PRs?

**Comment by tmuehl** [comment]
@rcillo yes, I think so

**Comment by v-stepanov** [comment]
:shipit:

**Pull request merged**
