### PR TITLE
set log level to INFO

### PR DESCRIPTION
**Pull request by adyach**
# One-line summary

set log level to INFO

### CODE REVIEW

**Comment by v-stepanov** [comment]
I checked current DEBUG logs in live nakadi. 
> 99% of DEBUG logs for last 4 hours were from classes "KafkaCrutchConsumer" and "ClosedConnectionsCrutch". I think if you lower log level for these two classes we will achieve the same log volume but we will keep valuable debug info for numerous endpoints.

**Comment by adyach** [comment]
As far as I understand debug level should be turned on for debugging purposes. which endpoints require debugging?

**Comment by antban** [comment]
:+1:

**Comment by v-stepanov** [comment]
@adyach 
422 for commit at least.
I think the work for this ticket should also include reviewing all places where we log with debug and deciding if this should be moved to info or not.

**Comment by adyach** [comment]
> I checked current DEBUG logs in live nakadi.
> > 99% of DEBUG log lines for last 4 hours were from classes "KafkaCrutchConsumer" and "ClosedConnectionsCrutch". I think if you lower log level for these two classes we will achieve the same log volume but we will keep valuable debug info for numerous endpoints.

done e4d8a7e

**Comment by v-stepanov** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by adyach** [comment]
👍

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
