### PR TITLE
Add a Contributing section to the Readme.

### LINKED ISSUE #262: Needs a contributors file or section in the README
For a good example, see: [](https://github.com/zalando/tracer/blob/master/CONTRIBUTING.md). It also helps to list 2-3 to-do's in the file or the README to more swiftly onboard new contributors; you can link to specific issues in the Issues Tracker, which is good for prioritizing for readers what you want done first.

### PR DESCRIPTION
**Pull request by dehora**
Fixes #262 

This is a basic contributor section and doesn't cover a todo list or target issues mentioned in #262.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/266" target="_blank">ReviewNinja

**Comment by LappleApple** [comment]
LGTM except a super-minor grammar thing--should be "community. Please"

**Comment by dehora** [comment]
>...should be "community. Please"

@LappleApple fixed in a1c4319

**Comment by rcillo** [comment]
@LappleApple can I merge it? Looks good for me 👍

**Pull request merged**
