### PR TITLE
Synchronize access to list created with synchronizedList when iterating

### PR DESCRIPTION
**Pull request by kinow**
Hello,

No ticket associated. Was just randomly looking at some code, and as recently worked on a ticket in another project for similar issue, remembered about this one.

I believe `ACQUIRED_SLOTS`, which was created with `Collections.synchronizedList`, must be accessed within a `synchronized` block when iterating, according to [Javadocs](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html).

Even though the javadocs for synchronizedList don't mention it, the synchronizedCollection mentions `streams()` as well as `Iterator`.

Hope that helps
Bruno

ps: Eclipse pointed that warning was not happening anymore. In case IntelliJ says otherwise, I'd be happy to put it back (though I suspect IntelliJ won't complain about it as well)

### CODE REVIEW

**Comment by lmontrieux** [comment]
Thank you for your contribution, @kinow . We will review it ASAP.

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
We have to fix our deployment script to validate this properly - sorry about the delay

**Comment by kinow** [comment]
Let me know if there's anything I can do to help. The coverage will decrease as there are more lines, even though they would be covered by previous tests.

**Comment by lmontrieux** [comment]
The issue is with the deployment process we use to validate pull requests. We have a fix ready, as soon as it is applied we will be able to validate your PR. Sorry for the delay.

**Comment by kinow** [comment]
I believe there are no more calls to Collections.synchronizedList in the project now. So closing the PR :grimacing:

**Pull request closed without merging**
