### PR TITLE
ARUHA-180 Update docker base image for local-storages

### PR DESCRIPTION
**Pull request by antban**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/230" target="_blank">ReviewNinja

**Comment by v-stepanov** [comment]
:shipit:

**Comment by antban** [comment]
I'm waiting for CI check :)

**Comment by rcillo** [comment]
Ci looks good. There's some annoying warning from codecov but never mind :shipit:

**Pull request merged**
