### PR TITLE
#951 Replace AuthMode.OFF by AuthMode.NONE

### PR DESCRIPTION
**Pull request by fbrns**
# AuthMode.NONE is added as an addition to AuthMode.OFF

## Description
When using application.yml to configure nakadi.oauth2.mode YAML parser translates OFF to false if it isn't put into quotes. Adding a NONE value in the enum that has the same effect as OFF prevents that and OFF can be kept for backward compatibility.

## Review
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by adyach** [comment]
@fbrns thank you for contribution!
can we just put `OFF` in quotes? I also see that this behaviour is changed for yaml 1.2, which interprets it as not a boolean. we have never observed such behaviour, most probably, the reason is that we use Nakadi with docker compose.

**Comment by fbrns** [comment]
Putting `OFF` into quotes could a quick but a bit awkward workaround (@cbornet, https://github.com/zalando/nakadi/issues/951). However with yaml 1.2 the situation will change somewhere in the future, but then a new state would not harm as well.

The behavior can be reproduced by removing `NAKADI_OAUTH2_MODE=OFF` from `docker-compose.yml` and adding `OFF` to `application.yml`.

**Comment by adyach** [comment]
@fbrns I do not understand why it is a problem to put it in quotes. From the other hand adding another identical auth mode looks like duplication and creates complication in understanding what purpose it serves. This state was created specifically for testing/debugging purposes thus it is used in conjunction with docker compose.

**Comment by fbrns** [comment]
The functionality is not needed, therefore I close the pull-request.

**Pull request closed without merging**
