### PR TITLE
Aruha 120 jvm instrumentation

### PR DESCRIPTION
**Pull request by tmuehl**
@v-stepanov @CyberDem0n @rcillo @jkliff Please review

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/156" target="_blank">ReviewNinja

**Comment by v-stepanov** [comment]
@tmuehl We have a test for metrics endpoint.
Do you want to extend it now? :)

**Comment by tmuehl** [comment]
@v-stepanov Oh, we have? Yes, of course!

**Comment by v-stepanov** [comment]
@tmuehl 
https://github.com/zalando/nakadi/blob/nakadi-jvm/src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/MetricsAT.java

**Comment by tmuehl** [comment]
@v-stepanov Looking at the test it doesn't really make sense for me to test that the jvm is intrumented. That's more on an operational level.

**Comment by v-stepanov** [comment]
@tmuehl as you wish.
In general such a test can make sense as it can test that we didn't fuckup the configuration, and metrics still work as we wanted and configured as we wanted. (E.g. like we fucked up snake_case serialisation in the past and didn't notice that)

**Comment by v-stepanov** [comment]
@tmuehl btw, build failed. Something wrong with gradle file
`> Could not find io.dropwizard.metrics:metrics-core:$dropwizardVersion.`

**Comment by v-stepanov** [comment]
:shipit:

**Pull request merged**
