### PR TITLE
ARUHA-277: Use checkstyle

### PR DESCRIPTION
**Pull request by v1ctor**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/317" target="_blank">ReviewNinja

**Comment by antban** [comment]
:shipit: :+1: :zapprit:

**Comment by v-stepanov** [comment]
I would also love to see a check that the line is not longer than 120 chars :)
But that will also force us to fix all places we violate that. As we now have a very big branch with HILA I would not like to add that check now because the merging will be a nightmare. Maybe later.

**Comment by v-stepanov** [comment]
:shipit:

**Comment by v-stepanov** [comment]
@antban your approval didn't work. I think it should be a comment with just a singe emoji.

**Comment by v-stepanov** [comment]
@v1ctor checkstyle task doesn't check the code in acceptance tests
Try to run `check` and it will find a lot of problems in acceptance tests

**Pull request merged**
