### PR TITLE
ARUHA-1203 Add delay (by default 2 seconds) between deletion of topics

### PR DESCRIPTION
**Pull request by antban**
[ARUHA-1203: Fix massive topic deletion]

## Description
Kafka may go down in case of deletion of many topics. 
To avoid that while switching timelines the timeout added between deletions

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
Just deploy it

### CODE REVIEW

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by antban** [comment]
deploy staging please

**Comment by antban** [comment]
deploy validation please

**Pull request merged**
