### PR TITLE
Aruha 134

### PR DESCRIPTION
**Pull request by v-stepanov**
- removed nakadi.read scope
- adjusted scope name to what we actually have
- removed trailing slash automapping to avoid security problems
@jkliff @CyberDem0n @rcillo @tmuehl @antban please review

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/207" target="_blank">ReviewNinja

**Comment by tmuehl** [comment]
@v-stepanov In which way do the trailing slashes raise security issues?

**Comment by v-stepanov** [comment]
@tmuehl 
Before my fix it was possible to avoid scope check by just adding "/" at the end of URL. As Spring by default maps that to URL without slash, and Spring security only checks the URL without slash at the end.

**Comment by tmuehl** [comment]
@v-stepanov Have you tried to put the more specific rule (e.g. `"/event-types/*/events"`) at the top and use `**` instead at the end of one rule, e.g.

```
.antMatchers(GET, "/event-types/*").access(hasScope(uidScope))
```

**Comment by v-stepanov** [comment]
@tmuehl I considered this possibility - to extend security masks with ** to cover more. But I think that can lead to different overlapping scenarios and to bugs as a result. I would prefer to have a more specific mask for each security role that covers exactly only endpoint itself.

**Comment by tmuehl** [comment]
@v-stepanov I think it would all work fine, if you put the more specific endpoints to the top. :)

**Comment by v-stepanov** [comment]
@tmuehl Yes, but that already makes you think about it and gives an opportunity to make a bug :)
Why do you prefer that? To keep the possibility to have `/` at the end?

**Comment by tmuehl** [comment]
@v-stepanov Yes, I like to have the possibility to be able to have a trailing slash. In the past I had cases when I was wondering what's going wrong when calling an endpoint and it turned out it was the missing / present trailing slash. I like to not need to think about if omitting the slash or not, if it is considered to be the same by the server. It can quickly lead to small but nerve-wracking bugs on the client side. But that's maybe my personally feelings, so feel free to ignore if you don't agree. :)

Particularly in cases where I expect the api to return a list of resources, i.e. where the resource is a bucket, it feels more natural for me to treat it like a directory, e.g. `/event-types/`.

Furthermore, what you suggest ist blacklisting, while restricting the entire endpoint `/event-types/**` and only set different access control settings for specific endpoints is whitelisting, what I prefer.

**Comment by v-stepanov** [comment]
@tmuehl 
I discussed that with api-guild, they also think that it's better to allow trailing slash as optional to be more flexible for the user who uses API. So I changed that back to optional "/" at the end, and I changed scopes masking to cover more with ** so that we don't have that security leak.

**Pull request merged**
