### PR TITLE
ARUHA-153 Remove Authorization header for localhost calls

### PR DESCRIPTION
**Pull request by tmuehl**
@rcillo @v-stepanov @jkliff @CyberDem0n @sezera Please review

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/183" target="_blank">ReviewNinja

**Comment by rcillo** [comment]
Maybe we should not try to validate the token when authentication is disabled. Then these instructions would be valid for all environments. Wdyt?

**Comment by tmuehl** [comment]
@rcillo I think, it's ok to validate it if it's provided. But I don't have a strong opinion about this.
Nevertheless it should be removed from the Readme.

Maybe it's worth to add an extra line in Readme telling about the Authorization. But the Readme on Github is not a Readme how to use the Zalando Services.

**Comment by rcillo** [comment]
@tmuehl ok. Since it's targeted in localhost, then it seems reasonable to remove it.

:shipit:

**Pull request merged**
