### PR TITLE
ARUHA-1640: improve light stats performance;

### PR DESCRIPTION
**Pull request by v-stepanov**
# Take partition list from ZK if possible

> Zalando ticket : ARUHA-1640

## Description
Now the list of partitions is taken from ZK node if it is present

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
-

### CODE REVIEW

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by adyach** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
👍

**Comment by rcillo** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
