### PR TITLE
Warn users about log compaction usage gotchas

### PR DESCRIPTION
**Pull request by rcillo**
https://techjira.zalando.net/browse/ARUHA-1819

Some organizations have strict guidelines on what type of data can or
cannot be stored permanently (log compacted means some data can be
potentially permanently stored).

This config opens space for configuring a message for users of the API.

### CODE REVIEW

**Comment by lmontrieux** [comment]
👍

**Comment by rcillo** [comment]
deploy validation please

**Comment by rcillo** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by rcillo** [comment]
👍

**Pull request merged**
