### PR TITLE
Documentation: Link to new homepage for nakadi-client for Haskell

### PR DESCRIPTION
**Pull request by mtesseract**
# One-line summary

Updated Nakadi documentation to refer to the new homepage of the nakadi-client package for Haskell instead of referring straight to the API documentation as published on Hackage.

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

## Deployment Notes
n/a

### CODE REVIEW

**Comment by lmontrieux** [comment]
Thank you for your contribution, @mtesseract . Is there any chance to get an https link?

**Comment by mtesseract** [comment]
I wish it was easy to get an https link. But this is hosted on github-pages with a custom domain name. As I understand https is not supported for this use-case at the moment.
:-(

**Comment by lmontrieux** [comment]
Cloudflare seems to be a better-than-nothing solution: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by mtesseract** [comment]
Will have a look at it. Thanks.
But I cannot estimate how much work this will involve and when I might be able to work on this.

**Comment by lmontrieux** [comment]
@mtesseract thank you. I'll approve this PR for now (it requires one more approval before it can be merged), but if/when you get around to looking this, it would be great if you could update this PR or open a new one.
Thank you again!

**Comment by lmontrieux** [comment]
👍

**Comment by mtesseract** [comment]
will do, thanks!

**Comment by v-stepanov** [comment]
👍

**Comment by lmontrieux** [comment]
I closed and re-opened this PR to trigger a travis build

**Pull request merged**
