### PR TITLE
Aruha 267 hila acceptance tests

### PR DESCRIPTION
**Pull request by v-stepanov**
@antban @adyach @rcillo please review
do you know any other interesting use-cases to test here?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/311" target="_blank">ReviewNinja

**Comment by antban** [comment]
Probably it will be interesting to test nakadi death. But I don't know how to implement it.

**Comment by antban** [comment]
:shipit:

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
@antban 
To test Nakadi death is only interesting when we have at least two Nakadi instances :) I believe this goes out of these acceptance tests scope.
Maybe at some point we will create a separate test-project that will test exclusively HILA in different possible ways.

**Pull request merged**
