### PR TITLE
Log 5xx even when access log is disabled

### PR DESCRIPTION
**Pull request by rcillo**
Not logging 5xx would make it difficult to catch bugs as the stack
trace would be lost.

This change also makes successful publishing request to be logged, so turning access log on should be done with care and only when needed, otherwise the log volume could be even bigger.

Do you think I should add another condition on top of these so that successful publishing requests are never logged?

### CODE REVIEW

**Comment by ferbncode** [comment]
I think it might be good to not log successful publishing even with the toggle turned on. There might be a huge increase in logs if we were to leave access logs open for an evening or weekend for finding possible bug. What do you think?

**Comment by rcillo** [comment]
@ferbncode I agree. It can see that happening very easily. I changed the conditional to also check that it's not a successful publishing request. 

So now we have access log in the following situations:

- it's a 5xx, regardless of which endpoint or feature toggles are turned on
- feature toggle is enabled and it's not a publishing request

It's quite complicated but I think it's the behaviour we are looking for to preserve easiness of debugging and not over log accidentally.

**Comment by rcillo** [comment]
@ferbncode I also turned on on test and local environment by default, so that when you are coding locally you can see access logs.

**Comment by ferbncode** [comment]
:+1:

**Comment by rcillo** [comment]
👍

**Pull request merged**
