### PR TITLE
Aruha-2121 Handle UnableProcessException properly in PostSubscriptionController

### PR DESCRIPTION
**Pull request by lmontrieux**
Also, improve method signature when UnableProcessException can be
thrown

# Handle UnableProcessException properly in PostSubscriptionController

> Zalando ticket : ARUHA-2121

## Description
Also, improve method signature when UnableProcessException can be
thrown

### CODE REVIEW

**Comment by v-stepanov** [comment]
@lmontrieux is it possible to add a controller test that tests this case?

**Comment by v-stepanov** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
