### PR TITLE
Added nakacli CLI client

### PR DESCRIPTION
**Pull request by amrhassan**
[ARUHA-774: Add nakacli CLI client to the client list](https://github.com/zalando/nakadi/issues/774)

## Description
I've added a row mentioning the project.

## Review
- [x] ~Tests~
- [x] Documentation
- [x] ~CHANGELOG~

## Deployment Notes
Nothing special

### CODE REVIEW

**Comment by lmontrieux** [comment]
Thank you for your PR, @amrhassan . It's nice to see people writing clients for Nakadi :)

**Comment by lmontrieux** [comment]
👍

**Comment by adyach** [comment]
👍

**Comment by lmontrieux** [comment]
I closed and re-opened this PR to force travis-ci to build it

**Pull request merged**
