### PR TITLE
Aruha 384 optimized nakadi

### PR DESCRIPTION
**Pull request by rcillo**
Reason for every change is in the respective commit. Actually, this is part of an experiment, so we are not merging it to master.

### CODE REVIEW

**Comment by adyach** [comment]
👍

**Comment by v-stepanov** [comment]
:shipit:

**Comment by v-stepanov** [comment]
BTW, why you create PR? Why you just not push that to experiment branch?

**Comment by rcillo** [comment]
@v-stepanov to share what's going on with you and get feedback.

**Comment by adyach** [comment]
@rcillo are we gonna merge this?

**Comment by rcillo** [comment]
@adyach not before we do some proper performance tests. I'll leave it open until we are done with the testing tool.

**Comment by adyach** [comment]
@rcillo do you think this one is still relevant to be opened ?

**Comment by rcillo** [comment]
@adyach seems like we did 2 out of 3 changes already. The only one missing is linger and I see no reasons to spend any more time on this.

**Pull request closed without merging**
