### PR TITLE
ARUHA-1997: Extended the catched exception range;

### PR DESCRIPTION
**Pull request by v-stepanov**
# One-line summary

> Zalando ticket : ARUHA-1997

## Description
For some reason (probably because of migrating to Hikari) in most cases we now have a different exception thrown when user tries to create ET that already exists. This is a fix for that problem.

## Review
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Comment by adyach** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
