### PR TITLE
[WIP] SplitByWeight Method Refactoring

### PR DESCRIPTION
**Pull request by satybald**
Could not resist to refactor splitByWeight method. It was using a greedy strategy with O(N^2)? algorithm. Refactored to strictly O(N) algorithms. The idea is simple: just accumulate a rounding error and carry it over to the next element.

### CODE REVIEW

**Comment by antban** [comment]
:+1: 
Actually it was O(N) as well, but now it misses this shitty comment, so I think that it is better

**Comment by antban** [comment]
:+1:

**Comment by satybald** [comment]
It was unclear if it runs in O(N) as it has two loops. do you know why CI are not running for this PR?

**Comment by satybald** [comment]
:+1:

**Comment by satybald** [comment]
can you guys please approve too? @rcillo @lmontrieux @adyach @v-stepanov

**Comment by adyach** [comment]
@satybald could you check why the build is failing? Looks like checkstyle,

**Comment by adyach** [comment]
@satybald some of the tests are still failing

**Comment by satybald** [comment]
thanks, @adyach. I'll take a look at it.

**Comment by adyach** [comment]
@satybald it is possible to run tests locally with 
```
./gradlew fullAcceptanceTest
./gradlew test
./gradlew checkstyle
```

**Comment by lmontrieux** [comment]
@satybald did you make progress on this? Is there any way we can help?

**Comment by satybald** [comment]
Unfortunately, I didn't much progress on this. They're a bunch of test failing in ExactWeightRebalancer.apply(). I should confess I don't really understand the logic going on in apply method.

**Comment by satybald** [comment]
In order to fix failing tests, would it be possible to document what invariants ExactWeightRebalancer.apply should preserve? It would be great if you could mention session state management.

**Comment by satybald** [comment]
Meanwhile, I have a question regarding rebalncer. Session 1, 2 have an equal number of partitions in the rebalanceShouldMoveToReassigningState test case. When rebalance is triggered either of them can be reassigned. Why only second is chosen in the [ExactWeightRebalancerTest](https://github.com/zalando/nakadi/blob/2690348c1a29431a160c542dfb2acaaab5d616e7/src/test/java/org/zalando/nakadi/service/subscription/ExactWeightRebalancerTest.java#L119)?

**Comment by satybald** [comment]
Could you please folks trigger the build @antban @adyach @lmontrieux? Style checks and units tests should pass now.

**Comment by lmontrieux** [comment]
@satybald I've reactivated builds for PR updates. Unfortunately, I think it will take pushing a commit (even a dummy one) to trigger a new build. Can you do that?

**Comment by lmontrieux** [comment]
@satybald Unfortunately the style check on tests seems to fail. Could you please have a look?

**Comment by satybald** [comment]
@lmontrieux the style check is not an issue per se. ```ExactWeightRebalancerTest.rebalanceShouldTakeReassigningPartition``` is still failing.

**Comment by lmontrieux** [comment]
@satybald there's a conflict in that file, between master and your branch. Maybe resolving it will help?

Also, for some reason travis doesn't want to report the status of the build, and I can't find it anywhere :-/

**Comment by lmontrieux** [comment]
There has been no activity on this PR since August 2017, and there are still conflicts that prevent it from being merged. Therefore, I will close this PR.
Please feel free to re-open it if you would like to continue working on it.

**Pull request closed without merging**
