### PR TITLE
ARUHA-1428: Added submitting of subscription log events;

### PR DESCRIPTION
**Pull request by v-stepanov**
[ARUHA-1428: Collect data as Nakadi event](https://techjira.zalando.net/browse/ARUHA-1428)

## Description
Added publishing of subscription log events. Will be used to calculate new subscription count KPI.

## Review
- [x] Tests
- [ ] Documentation
- [x] CHANGELOG

## Deployment Notes
-

### CODE REVIEW

**Comment by SergKam** [comment]
:+1:

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
👍

**Comment by rcillo** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
