### PR TITLE
ARUHA-633 Disable consumer offset auto commit

### PR DESCRIPTION
**Pull request by lmontrieux**
This PR sets enable.auto.commit to false

### CODE REVIEW

**Comment by rcillo** [comment]
@lmontrieux as we talked previously, I have some questions:

1. is it safe to remove `__consumer_offsets` partition after disabling this feature?
2. when creating a new cluster, if this feature is never used, does it create `__consumer_offsets` automatically? When is this partition created?
3. when validating the impact of this change, is it possible to observe any changes in "bytes/flow" for this specific topic?

**Comment by rcillo** [comment]
@lmontrieux don't you have to manually call `seek` to update the position to read on the next `poll` operation?

**Comment by v-stepanov** [comment]
@rcillo I think we can test that quite easy.

**Comment by lmontrieux** [comment]
@rcillo 

About 2.
It is created at startup, but it stays empty (confirmed locally)

Will update about the other questions

**Comment by lmontrieux** [comment]
@rcillo looks like we only need to call `seek` upon restarting the client:

```
On restart restore the position of the consumer using seek(TopicPartition, long).
```

**Comment by lmontrieux** [comment]
@rcillo for 1., I don't know, but I'll check in a sandbox.
For 3., I suspect that it is the case, since data replication is counted. In any case we can also connect to the kafka node that's leader for the partition, and consume from it to make sure nothing is written there anymore.

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
