### PR TITLE
aruha-1518: thread safe usage of MessageDigest

### PR DESCRIPTION
**Pull request by adyach**
Thread safe usage of MessageDigest

> Zalando ticket : aruha-1518

## Description
Thread safe usage of MessageDigest

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

### CODE REVIEW

**Comment by antban** [comment]
:+1:

**Comment by adyach** [comment]
👍

**Comment by adyach** [comment]
deploy validation please

**Comment by adyach** [comment]
deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Comment by antban** [comment]
:+1:

**Pull request merged**
