### PR TITLE
Aruha 1624 out of memory

### PR DESCRIPTION
**Pull request by v-stepanov**
# Fixed out of memory problem

> OutOfMemoryError in case of using very large max_uncommitted_events and batch_limit : ARUHA-1624

## Description
Fixed OutOfMemoryError when using huge values for batch_limit and max_uncommitted_events

## Review
- [ ] Tests
- [ ] Documentation
- [x] CHANGELOG

## Deployment Notes
-

### CODE REVIEW

**Comment by v-stepanov** [comment]
👍

**Comment by v-stepanov** [comment]
deploy validation please

**Comment by v-stepanov** [comment]
👍

**Comment by rcillo** [comment]
👍

**Pull request merged**
