### PR TITLE
Mocking up Principal instead of using com.sun package

### PR DESCRIPTION
**Pull request by cesarcneto**
Mocking up Principal instead of using com.sun.security.auth.UserPrincipal class

### CODE REVIEW

**Comment by LappleApple** [comment]
Hi @cesarcneto: Thank you for your interest in Nakadi! Looks like nobody has acknowledged your PR yet; sorry about that. Doing it now. :) 

Hey @v-stepanov @rcillo @valgog @adyach @v1ctor @antban: Can one of you guys get back to this contributor ASAP stating whether you plan to merge or reject his work? Thanks!

**Comment by cesarcneto** [comment]
This is just a tiny contribution, should be pretty straight forward to merge it.
Thx!

**Comment by adyach** [comment]
@cesarcneto hi, could you please resolve conflicts ?

**Comment by cesarcneto** [comment]
@adyach  it should be done by now. Hope it helps. Thx

**Comment by cesarcneto** [comment]
Ah, just noticed that it could also be applied to StoragesControllerTest... Hold on!

**Comment by cesarcneto** [comment]
@adyach please, check that out. Thanks!

**Comment by adyach** [comment]
@cesarcneto looks nice! you have things to improve here https://www.codacy.com/app/stepanov-vyacheslav/nakadi/pullRequest?prid=467471. I think it will fail the build anyway.
Thanks!

**Comment by cesarcneto** [comment]
@adyach can improve that. Just leave it open for now. What do you think?

**Comment by adyach** [comment]
@cesarcneto it is not possible to merge it, because the build is failing. the reason is that checkstyle did not pass. i can leave the PR opened.

**Comment by cesarcneto** [comment]
@adyach looks good now.

**Comment by adyach** [comment]
👍

**Comment by LappleApple** [comment]
@adyach: Hi, this PR could be merged if you approve...

**Comment by adyach** [comment]
@LappleApple it is approved with 👍 , so, please, merge it :)

**Pull request merged**
