### PR TITLE
ARUHA-1887 Refactor exceptions

### PR DESCRIPTION
**Pull request by lmontrieux**
# Refactor nakadi exceptions
> Zalando ticket : ARUHA-1887

## Description
This PR refactors the Nakadi exceptions so that:
- they are all runtime
- they inherit MyNakadiRuntimeException1, which in turn is renamed to something more acceptable
- there are no more HTTP response codes in exceptions

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

### CODE REVIEW

**Comment by adyach** [comment]
I went through the changes, LGTM

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
Deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by adyach** [comment]
👍

**Pull request merged**
