### PR TITLE
ARUHA-1449: Collect data as Nakadi event

### PR DESCRIPTION
**Pull request by adyach**
[ARUHA-1449: Collect data as Nakadi event](https://techjira.zalando.net/browse/ARUHA-1449)

## Description
Nakaid KPI extension for tracking feature adoption 

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

### CODE REVIEW

**Comment by v-stepanov** [comment]
looks good to me.

**Comment by v-stepanov** [comment]
👍

**Comment by adyach** [comment]
👍

**Comment by adyach** [comment]
deploy validation please

**Pull request merged**
