### PR TITLE
aruha-1170: validate stream id

### PR DESCRIPTION
**Pull request by adyach**
[ARUHA-1170: Committing with empty X-Nakadi-StreamId causes 503](https://techjira.zalando.net/browse/ARUHA-1170)

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

### CODE REVIEW

**Comment by rcillo** [comment]
👍

**Comment by adyach** [comment]
👍

**Comment by adyach** [comment]
deploy validation please

**Comment by adyach** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by adyach** [comment]
👍

**Pull request merged**
