### PR TITLE
Optimize list subscription query

### PR DESCRIPTION
**Pull request by samizzy**
Alternate PR for improving list subscription as pagination is not required for dealing with list of subscriptions internally.

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by samizzy** [comment]
:+1:

**Comment by adyach** [comment]
> Alternate PR for improving list subscription as pagination is not required for dealing with list of subscriptions internally

@samizzy could elaborate on the change please ?

**Comment by samizzy** [comment]
> > Alternate PR for improving list subscription as pagination is not required for dealing with list of subscriptions internally
> 
> @samizzy could elaborate on the change please ?

1. The use of paginated querying of subscription was unnecessary in the the current code when used internally, hence subscription query generation code has been made to optionally accept Pagination params instead of mandatorily asking for it.
2. Currently, the check for listing subscriptions during deleting a eventtype is a 2 part process (involves calling select 2 times once when checking for subscription and other when deleting) which is not needed and could lead to inconsistent results. Now this is done inside a transaction.

**Comment by a1exsh** [comment]
> Now querying is done once then deletion both of them done inside a transaction.

Yeah, actually it's 2 changes in one, and this is the more important part of it, IMO :D

**Comment by adyach** [comment]
> > > Alternate PR for improving list subscription as pagination is not required for dealing with list of subscriptions internally
> > 
> > 
> > @samizzy could elaborate on the change please ?
> 
> 1. The use of paginated querying of subscription was unnecessary in the the current code when used internally, hence subscription query generation code has been made to optionally accept Pagination params instead of mandatorily asking for it.
> 2. Currently, the check for listing subscriptions during deleting a eventtype is a 2 part process (involves calling select 2 times once when checking for subscription and other when deleting) which is not needed and could lead to inconsistent results. Now querying is done once then deletion both of them done inside a transaction.

@samizzy thanks, please, add details in commit message when merging to master

**Pull request merged**
