### PR TITLE
Correct Code of conduct

### PR DESCRIPTION
**Pull request by zrobgar**
ARUHA-931: https://techjira.zalando.net/browse/ARUHA-931 Add Code of conduct

## Description
Add Code of conduct and correct indention
commits.

### CODE REVIEW

**Comment by lmontrieux** [comment]
I don't think this requires a changelog entry so I'll approve it

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
However, it does need a ticket number in the description, for compliance

**Comment by zrobgar** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
