### PR TITLE
ARUHA-50 Using snake case instead of camel case

### PR DESCRIPTION
**Pull request by rcillo**
Due to a spring boot problem, the wrong mapper bean is wired during application boot. That causes an issue where camel cases are not properly mapped to snake case.

So I'm explicitly mapping properties as snake case.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zalando/nakadi/pull/102" target="_blank">ReviewNinja

**Comment by rcillo** [comment]
I had seem the docs http://docs.spring.io/spring-boot/docs/current/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper but it just doesn't work.

**Comment by v-stepanov** [comment]
@rcillo 
In general we do have a global config for that here https://github.com/zalando/nakadi/blob/nakadi-jvm/src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java#L72
Would be great if you can find a reason why it stopped working :)
Because owningApplication property is not the only place where it is broken. For class https://github.com/zalando/nakadi/blob/nakadi-jvm/src/main/java/de/zalando/aruha/nakadi/domain/TopicPartition.java
it also works wrong now (with camel-case)

**Comment by rcillo** [comment]
@v-stepanov sure. I'm going to further investigate this issue :+1:

**Comment by rcillo** [comment]
We are going to provide a general solution for this problem.

**Pull request closed without merging**
