### PR TITLE
ARUHA-392: fixed jacoco report dependency

### PR DESCRIPTION
**Pull request by v-stepanov**

### CODE REVIEW

**Comment by adyach** [comment]
@v-stepanov it failed to build with an error:
FAILURE: Build failed with an exception.
* What went wrong:
Circular dependency between the following tasks:
:jacocoTestReport
\--- :test
     \--- :jacocoTestReport (*)

(*) - details omitted (listed previously)

**Comment by v-stepanov** [comment]
@adyach yeah, I know. I'm fixing it now.

**Comment by adyach** [comment]
there is a possibility to add it to the test task, but this one is good as well 👍

**Comment by v-stepanov** [comment]
@adyach hey, approval emoji should be a separate comment, in other case zappr doesn't recognize it :(

**Comment by adyach** [comment]
👍

**Pull request merged**
