### PR TITLE
ARUHA-1275 Upgrade json-schema, take 2

### PR DESCRIPTION
**Pull request by lmontrieux**
Also revert one change in the meta-schema as a result

## Description
Second attempt at upgrading the json-schema library, after a regression was found in URI validation

## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

### CODE REVIEW

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Comment by lmontrieux** [comment]
deploy validation please

**Comment by lmontrieux** [comment]
👍

**Comment by adyach** [comment]
👍

**Pull request merged**
