### PR TITLE
Add missing OAuth2 to registry

### PR DESCRIPTION
**Pull request by mastersimon**
- add oauth2 to _registry/validation-strategies_
- add oauth2 to _registry/enrichment-strategies_
- add oauth2 to _registry/partition-strategies_

### CODE REVIEW

**Comment by adyach** [comment]
@mastersimon thank you for contribution! I think having `nakadi.event_stream.read` for reading some configuration data is not the right approach. I do not know exactly what was the intention for `nakadi.config` scopes but I propose to use `nakadi.config.read` for `registry` endpoint. Also there is a possibility that someone is already using `nakadi.event_stream.read` scope then we do not have many choices here. WDYT, @antban, @rcillo, @v1ctor, @v-stepanov ?

**Comment by mastersimon** [comment]
Hi @adyach,

my approach was to add OAuth to the endpoints - because you need it. Per attention I added `nakadi.event_stream.read`. Of course I can change it to whatever makes sense.

**Comment by adyach** [comment]
@mastersimon at least it shows current situation with the api, please, resolve conflicts and I will merge it. thanks!

**Comment by adyach** [comment]
👍

**Pull request merged**
