### PR TITLE
ARUHA-1360 Add crutch for being able to change category of event type from NONE to BUSINESS

### PR DESCRIPTION
**Pull request by antban**
[ARUHA-1360: Be able to change EventType category from NONE to BUSINESS]

## Description
Some people want to be able to change event type category from NONE to BUSINESS.
The simplest way to do it is to allow this change in nakadi
## Review
- [ ] Tests
- [ ] Documentation
- [ ] CHANGELOG

### CODE REVIEW

**Comment by rcillo** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by antban** [comment]
deploy validation please

**Comment by rcillo** [comment]
👍

**Comment by antban** [comment]
deploy validation please

**Comment by antban** [comment]
:+1:

**Comment by antban** [comment]
:+

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Comment by antban** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
